Rails/Projekte/unterricht/config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  
  resources :books  do
  	resources :likes
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
end

Rails/Projekte/unterricht/app/models/book.rb
class Book < ApplicationRecord
	has_many :likes
end

Rails/Projekte/unterricht/app/models/like.rb
class Like < ApplicationRecord
  belongs_to :book
  validates :quality, numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5}
end

Rails/Projekte/unterricht/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:author, :title, :description, :published_on)
    end
end

Rails/Projekte/unterricht/app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: [:show, :edit, :update, :destroy]
  before_action :set_book

  # GET /likes
  # GET /likes.json
  def index
    @likes = @book.likes
  end

  # GET /likes/1
  # GET /likes/1.json
  def show
  end

  # GET /likes/new
  def new
    @like = @book.likes.new
  end

  # GET /likes/1/edit
  def edit
  end

  # POST /likes
  # POST /likes.json
  def create
    @like = @book.likes.new(like_params)

    respond_to do |format|
      if @like.save
        format.html { redirect_to book_like_path(@book.id, @like.id), notice: 'Like was successfully created.' }
        format.json { render :show, status: :created, location: @like }
      else
        format.html { render :new }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /likes/1
  # PATCH/PUT /likes/1.json
  def update
    respond_to do |format|
      if @like.update(like_params)
        format.html { redirect_to book_like_path(@book.id, @like.id), notice: 'Like was successfully updated.' }
        format.json { render :show, status: :ok, location: @like }
      else
        format.html { render :edit }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /likes/1
  # DELETE /likes/1.json
  def destroy
    @like.destroy
    respond_to do |format|
      format.html { redirect_to book_likes_url(@book.id), notice: 'Like was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_like
      @like = Like.find(params[:id])
    end

    def set_book
        @book = Book.find(params[:book_id])
      
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def like_params
      params.require(:like).permit(:quality, :book_id)
    end
end

Rails/Projekte/unterricht/app/helpers/books_helper.rb
module BooksHelper
end

Rails/Projekte/unterricht/app/views/books/_form.html.erb
<%= form_for(book) do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :published_on %>
    <%= f.date_select :published_on %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Rails/Projekte/unterricht/app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

Rails/Projekte/unterricht/app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Title</th>
      <th>Description</th>
      <th>Published on</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.author %></td>
        <td><%= book.title %></td>
        <td><%= book.description %></td>
        <td><%= book.published_on %></td>
        <td><%= link_to 'Show', book %></td>

        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Likes', book_likes_path(book.id) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

Rails/Projekte/unterricht/app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

Rails/Projekte/unterricht/app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Published on:</strong>
  <%= @book.published_on %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

Rails/Projekte/unterricht/app/views/layouts/_top_bar.html.erb
<div class="top-bar">
  <div class="top-bar-title">
    <span data-responsive-toggle="responsive-menu" data-hide-for="medium">
      <button class="menu-icon dark" type="button" data-toggle></button>
    </span>
    <a>Book Shop</a>
  </div>
  <div id="responsive-menu">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li>
          <a href="<%= root_path %>">Startseite</a>

        
      
    </div>
    
  </div>
</div>

Rails/Projekte/unterricht/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <%= javascript_include_tag "vendor/modernizr" %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

  <%= image_tag 'logo.jpg' %>

  <%= render "layouts/top_bar" %>

    <%= yield %>

  </body>
</html>

Rails/Projekte/unterricht/app/views/likes/_form.html.erb
<%= form_for([@book,@like]) do |f| %>
  <% if like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(like.errors.count, "error") %> prohibited this like from being saved:</h2>

      <ul>
      <% like.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quality %>
    <%= f.number_field :quality %>
  </div>



    <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Rails/Projekte/unterricht/app/views/likes/edit.html.erb
<h1>Editing Like</h1>

<%= render 'form', like: @like %>

<%= link_to 'Show', @like %> |
<%= link_to 'Back', likes_path %>

Rails/Projekte/unterricht/app/views/likes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Likes</h1>

<table>
  <thead>
    <tr>
      <th>Quality</th>
      <th>Book</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @likes.each do |like| %>
      <tr>
        <td><%= like.quality %></td>
        <td><%= like.book %></td>
        <td><%= like.description %></td>
        <td><%= link_to 'Show', book_like_path(@book.id, like.id) %></td>
        <td><%= link_to 'Edit', edit_book_like_path(@book.id, like.id) %></td>
        <td><%= link_to 'Destroy', book_like_path(@book.id, like.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Like', new_book_like_path %>

Rails/Projekte/unterricht/app/views/likes/new.html.erb
<h1>New Like</h1>

<%= render 'form', like: @like %>

<%= link_to 'Back', book_likes_path(@book.id) %>

<%#=               %>

Rails/Projekte/unterricht/app/views/likes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quality:</strong>
  <%= @like.quality %>
</p>

<p>
  <strong>Book:</strong>
  <%= @like.book %>
</p>

<%= link_to 'Edit', edit_book_like_path(@like) %> |
<%= link_to 'Back', book_likes_path %>