Rails/Projekte/ontrack/config/routes.rb
Rails.application.routes.draw do

  resources :projects do 
  resources :iterations

end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Rails/Projekte/ontrack/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Rails/Projekte/ontrack/app/models/iteration.rb
class Iteration < ApplicationRecord
  belongs_to :project
end

Rails/Projekte/ontrack/app/models/project.rb
class Project < ApplicationRecord

validates :title, presence: true

has_many :iterations

end

Rails/Projekte/ontrack/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Rails/Projekte/ontrack/app/controllers/iterations_controller.rb
class IterationsController < ApplicationController
  before_action :set_iteration, only: [:show, :edit, :update, :destroy]
  before_action :set_project 

  # GET /iterations
  # GET /iterations.json
  def index
    @iterations = @project.iterations
  end

  # GET /iterations/1
  # GET /iterations/1.json
  def show
  end

  # GET /iterations/new
  def new
    @iteration = @project.iterations.new
  end

  # GET /iterations/1/edit
  def edit
  end

  # POST /iterations
  # POST /iterations.json
  def create
    @iteration = @project.iterations.new(iteration_params)

    respond_to do |format|
      if @iteration.save
        format.html { redirect_to project_iterations_path(@project.id, @iteration.id), notice: 'Iteration was successfully created.' }
        format.json { render :show, status: :created, location: @iteration }
      else
        format.html { render :new }
        format.json { render json: @iteration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /iterations/1
  # PATCH/PUT /iterations/1.json
  def update
    respond_to do |format|
      if @iteration.update(iteration_params)
        format.html { redirect_to project_iterations_path(@project.id, @iteration.id), notice: 'Iteration was successfully updated.' }
        format.json { render :show, status: :ok, location: @iteration }
      else
        format.html { render :edit }
        format.json { render json: @iteration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /iterations/1
  # DELETE /iterations/1.json
  def destroy
    @iteration.destroy
    respond_to do |format|
      format.html { redirect_to project_iterations_url(@project.id), notice: 'Iteration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_iteration
      @iteration = Iteration.find(params[:id])
    end

   def set_project
              @project = Project.find(params[:project_id]) #### vor params einfügen
            
        end

    # Never trust parameters from the scary internet, only allow the white list through.
    def iteration_params
      params.require(:iteration).permit(:title, :description, :start_date, :end_date, :project_id, :project_id)
    end
end

Rails/Projekte/ontrack/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :start_date, :end_date)
    end
end

Rails/Projekte/ontrack/app/helpers/application_helper.rb
module ApplicationHelper
end

Rails/Projekte/ontrack/app/helpers/iterations_helper.rb
module IterationsHelper
end

Rails/Projekte/ontrack/app/helpers/projects_helper.rb
module ProjectsHelper
end

Rails/Projekte/ontrack/app/views/iterations/_form.html.erb
<%= form_for([@project, @iteration]) do |f| %>
  <% if iteration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(iteration.errors.count, "error") %> prohibited this iteration from being saved:</h2>

      <ul>
      <% iteration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :start_date %>
    <%= f.datetime_select :start_date %>
  </div>

  <div class="field">
    <%= f.label :end_date %>
    <%= f.datetime_select :end_date %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Rails/Projekte/ontrack/app/views/iterations/edit.html.erb
<h1>Editing Iteration</h1>

<%= render 'form', iteration: @iteration %>

<%= link_to 'Show', project_iteration_path(@project.id, @iteration.id) %> |
<%= link_to 'Back', project_iterations_path(@project.id) %>

Rails/Projekte/ontrack/app/views/iterations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Iterations</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Project</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @iterations.each do |iteration| %>
      <tr>
        <td><%= iteration.title %></td>
        <td><%= iteration.description %></td>
        <td><%= iteration.start_date %></td>
        <td><%= iteration.end_date %></td>
        <td><%= iteration.project_id %></td>
        <td><%= iteration.project %></td>
        <td><%= link_to 'Show', project_iteration_path(@project.id, iteration.id) %></td>
        <td><%= link_to 'Edit', edit_project_iteration_path(@project.id, iteration.id) %></td>
        <td><%= link_to 'Destroy', project_iteration_path(@project.id, iteration.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Iteration', new_project_iteration_path %>

Rails/Projekte/ontrack/app/views/iterations/new.html.erb
<h1>New Iteration</h1>

<%= render 'form', iteration: @iteration %>

<%= link_to 'Back', project_iterations_path(@project.id) %>

Rails/Projekte/ontrack/app/views/iterations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @iteration.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @iteration.description %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @iteration.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @iteration.end_date %>
</p>

<p>
  <strong>Project:</strong>
  <%= @iteration.project_id %>
</p>

<p>
  <strong>Project:</strong>
  <%= @iteration.project %>
</p>

<%= link_to 'Edit', edit_project_iteration_path(@iteration) %> |
<%= link_to 'Back', project_iteration_path %>

Rails/Projekte/ontrack/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <%= javascript_include_tag "vendor/modernizr" %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

Rails/Projekte/ontrack/app/views/projects/_form.html.erb
<%= form_for(project) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :start_date %>
    <%= f.text_field :start_date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Rails/Projekte/ontrack/app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

Rails/Projekte/ontrack/app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= pluralize(@projects.count, "Project", plural: "Projects" ) %></h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= truncate(project.description, length: 10) %></td>
        <td><%= project.start_date %></td>
        <td><%= project.end_date %></td>
        <td><%= link_to 'Iterations', project_iterations_path(project) %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

Rails/Projekte/ontrack/app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

Rails/Projekte/ontrack/app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @project.start_date %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>