Rails/Projekte/flix/config/routes.rb
Rails.application.routes.draw do
  
	root 'movies#index'
	get 'signup' => 'users#new'
	
	resource :session
  resources :users
	resources :movies do
		resources :favourites
		resources :reviews
	end	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end
 

Rails/Projekte/flix/app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :movie
  belongs_to :user
end

Rails/Projekte/flix/app/models/movie.rb
class Movie < ApplicationRecord
	has_many :reviews, dependent: :destroy
	has_many :favourites, dependent: :destroy
	has_many :favouriter, through: :favourites, source: :user
end
 

Rails/Projekte/flix/app/models/review.rb
class Review < ApplicationRecord
	belongs_to :movie
end

Rails/Projekte/flix/app/models/user.rb
class User < ApplicationRecord
  has_secure_password


  	has_many :ratings, :dependent => :destroy
  	has_many :favourites, dependent: :destroy
  	has_many :favourited_movies, through: :favourites, source: :movie

  validates :name ,presence: true
  validates :email ,presence: true, format: { with: /(\S+)@(\S+)/ }, uniqueness: { case_sensitive: false }

end

Rails/Projekte/flix/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def current_user
  	User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  	def require_signin
		unless current_user
			redirect_to new_session_url, alert: "Please sign in first!!!"
		end
	end
end

Rails/Projekte/flix/app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
	def create
		@movie = Movie.find(params[:movie_id])
		unless Favourite.where(user_id: current_user.id, movie_id: @movie.id).any?
			@movie.favourites.create(user_id: current_user.id)
			redirect_to @movie, notice: "Movie wurde geliked"
	else 
		redirect_to @movie, alert: "Mehrmals-Like is not really möglich"
		end 
		
	end
	def destroy
		@favourite = Favourite.find(params[:id])
		@favourite.delete
		redirect_to movie_path(params[:movie_id]), alert: "Du hasst erfolgreich einen Dissliked Button gedrückt"	

	end 
end

Rails/Projekte/flix/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	before_action :set_movie, only: [:show, :edit, :update, :destroy]
	before_action :require_signin, :except => [:index]
	def index
		@movies = Movie.all
	end

	def show 
  		@favouriter = @movie.favouriter
	end

	def new
		@movie = Movie.new
	end

	def create
		@movie = Movie.new(movie_params)
		if @movie.save
			redirect_to movies_path
		else 
			render :new
		end
	end

	def edit
 
	end

	def update
		@movie.update(movie_params)
		redirect_to movies_path
	end

	def destroy
		@movie.destroy
		redirect_to movies_path
	end

	private
		def set_movie
			@movie = Movie.find(params[:id])
		end
		def movie_params
			params.require(:movie).permit(:name, :description, :released_on)
		end
end
  

Rails/Projekte/flix/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_movie
  before_action :require_signin

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = @movie.reviews
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end 

  # GET /reviews/new 
  def new
    @review = @movie.reviews.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json 
  def create
    @review = @movie.reviews.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to movie_review_path(@movie.id, @review.id), alert: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to  movie_review_path(@movie.id, @review.id) , notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to movie_reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def set_movie
      @movie = Movie.find(params[:movie_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:name, :stars, :comment, :movie_id)
    end
end

Rails/Projekte/flix/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end
	def create
		user = User.find_by(email: params[:email])	#prüft ob email in DB vorhanden ist
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			flash[:notice] = "Welcome back #{user.name}."
			redirect_to root_path
		else
			flash.now[:alert]	#speicher die Fehlinformation im hintergrund für den render
			render :new 	# gehe zu views/sessions/new.html.erb
		end
	end
	def destroy
		session[:user_id] = nil
		redirect_to root_path, notice: "Ausgeloggt. Bye, bye love."
	end
end

Rails/Projekte/flix/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_signin, :except => [:new, :create]
  before_action :require_correct_user, only: [:edit, :update, :destroy]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
      @favourited_movies = @user.favourited_movies
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def require_correct_user
      unless current_user == @user
        redirect_to users_url, alert: "No permission!"
      end
    end
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

Rails/Projekte/flix/app/helpers/favourites_helper.rb
module FavouritesHelper
end

Rails/Projekte/flix/app/helpers/movies_helper.rb
module MoviesHelper
end

Rails/Projekte/flix/app/helpers/reviews_helper.rb
module ReviewsHelper
end

Rails/Projekte/flix/app/helpers/sessions_helper.rb
module SessionsHelper
end

Rails/Projekte/flix/app/helpers/users_helper.rb
module UsersHelper
end

Rails/Projekte/flix/app/views/layouts/_flash_messages.html.erb
<div class="panel">
	<% flash.each do |key, value| %>
		<%= content_tag(:p, value, :class => "flash_#{key}") %>
	<% end %>
</div>

Rails/Projekte/flix/app/views/layouts/_side_bar.html.erb
<h4>Sidebar hier</h1>

Rails/Projekte/flix/app/views/layouts/_top_bar.html.erb
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">Flix APP</li>
      <li><%= link_to 'Projekte', root_path %></li>
      <li><%= link_to 'Admin', root_path %></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <% if current_user %>
        <%= current_user.name.capitalize %>
        <%= link_to 'Logout', session_path, method: :delete %>
        <% else %>
      <li><%= link_to 'Sign Up', signup_path %></li>
      <li><%= link_to 'Sign In', new_session_path %></li>
      <% end %>
    </ul>
  </div>
</div>

Rails/Projekte/flix/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row">
      <div class="row float-right">
        <%= image_tag 'logo.png' %>
      </div>
      <div class="clearfix">
      </div>
      <%= render 'layouts/top_bar' %>
      <div class="row">
        <%= render 'layouts/flash_messages' %>
        <div class="medium-3 columns">
          <%= render 'layouts/side_bar' %>
        </div>
        <div class="medium-9 columns">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

Rails/Projekte/flix/app/views/reviews/_form.html.erb
<%= form_for([@movie, @review]) do |f| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %> 

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :stars %>
    <%= f.number_field :stars %>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_area :comment %>
  </div>

  <div class="field">
    <%= f.label :movie_id %>
    <%= f.number_field :movie_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Rails/Projekte/flix/app/views/reviews/edit.html.erb
<h1>Edit review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', movie_review_path(@movie.id, @review.id) %> |
<%= link_to 'Back', movie_reviews_path(@movie.id) %>
   

Rails/Projekte/flix/app/views/reviews/index.html.erb
<h1>Reviews</h1>

<table> 
  <thead>
    <tr>
      <th>Name</th>
      <th>Stars</th>
      <th>Comment</th>
      <th>Movie</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <h3>for <%= @movie.name %></h3>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.name %></td>
        <td><%= review.stars %></td>
        <td><%= review.comment %></td>
        <td><%= review.movie_id %></td>
        <td><%= link_to 'Show', movie_review_path(@movie.id, review.id) %></td> 
        <td><%= link_to 'Edit', edit_movie_review_path(@movie.id, review.id) %></td>
        <td><%= link_to 'Destroy',  movie_review_path(@movie.id, review.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New review', new_movie_review_path(@movie.id) %><br>
<%= link_to "Back to movie", movie_path(@movie.id) %>

Rails/Projekte/flix/app/views/reviews/new.html.erb
<h1>New Review for <%= @movie.name %></h1>

<%= render 'form', review: @review %>
<%= link_to 'Back', movie_reviews_path(@movie.id) %>
   

Rails/Projekte/flix/app/views/reviews/show.html.erb
<h2><%= @movie.name %></h2>

<p>
  <strong>Name:</strong>
  <%= @review.name %>
</p>

<p>
  <strong>Stars:</strong>
  <%= @review.stars %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<p>
  <strong>Movie:</strong>
  <%= @review.movie_id %>
</p>




<%= link_to 'Edit', edit_movie_review_path(@movie.id, @review.id) %> |
<%= link_to 'Back', movie_reviews_path(@movie.id) %>
    

Rails/Projekte/flix/app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Rails/Projekte/flix/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

Rails/Projekte/flix/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

Rails/Projekte/flix/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

Rails/Projekte/flix/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

	<% if @favourited_movies.any? %>
		<h3>Liked Movies</h3>

			<p>
				<ul>
					<% @favourited_movies.each do |movie| %>
						<li><%= movie.title %></li>
					<% end %>
				</ul>

			</p>
	<% end %>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>